import { ProjectFullArchive } from "@/app/types/projectComponentTypes/projectFullArchive";

export const projectFullArchive: ProjectFullArchive[] = [
  {
    year: 2024,
    name: "My Portfolio",
    personnel: 1,
    techStack: ["Next.js", "TypeScript", "Emotion"],
    link: "https://my-portfolio-snowy-tau.vercel.app/",
  },
  {
    year: 2024,
    name: "Palette*",
    personnel: 6,
    techStack: [
      "Next.js",
      "TypeScript",
      "Emotion",
      "React-query",
      "Zustand",
      "Github Actions",
    ],
    link: "https://github.com/Happiness-Meta/final-front",
  },
  {
    year: 2024,
    name: "Earth-IDE-N",
    personnel: 6,
    techStack: [
      "React",
      "vite",
      "TypeScript",
      "SCSS",
      "React-query",
      "Zustand",
    ],
    link: "https://github.com/Happiness-Meta/web-ide-front",
  },
  {
    year: 2024,
    name: "ZAC",
    personnel: 4,
    techStack: ["React", "JavaScript"],
    link: "https://github.com/zoom-project-frontend/zoom-project-frontend_CK",
  },
  {
    year: 2023,
    name: "CPK Note",
    personnel: 3,
    techStack: ["Next.js", "TypeScript", "SCSS", "Redux"],
    link: "https://github.com/Matilda0730/231208-goormtoy2-noteapp?tab=readme-ov-file",
  },
  {
    year: 2023,
    name: "I'm Lucky Today",
    personnel: 3,
    techStack: ["React", "TypeScript", "Zustand"],
    link: "https://github.com/BearWithpy/goorm_horoscope_today",
  },
  {
    year: 2023,
    name: "Shopping Mall with React",
    personnel: 1,
    techStack: ["React", "JavaScript", "Zustand", "Firebase"],
    link: "https://github.com/HermannChoi/GR6",
  },
  {
    year: 2023,
    name: "Budget Calculator",
    personnel: 1,
    techStack: ["React", "JavaScript"],
    link: "https://github.com/HermannChoi/GR5",
  },
  {
    year: 2023,
    name: "GitHub Finder",
    personnel: 1,
    techStack: ["HTML", "CSS", "JavaScript"],
    link: "https://github.com/HermannChoi/GR3",
  },
  {
    year: 2023,
    name: "Todo with JS",
    personnel: 1,
    techStack: ["HTML", "CSS", "JavaScript"],
    link: "https://github.com/HermannChoi/GR2",
  },
  {
    year: 2023,
    name: "Netflix clone coding",
    personnel: 1,
    techStack: ["HTML", "CSS"],
    link: "https://github.com/HermannChoi/GoormAssignment",
  },
];
